.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. deepcoin_qt test_deepcoin_qt
clean: FORCE
	$(MAKE) -C .. deepcoin_qt_clean test_deepcoin_qt_clean
check: FORCE
	$(MAKE) -C .. test_deepcoin_qt_check
deepcoin-qt deepcoin-qt.exe: FORCE
	 $(MAKE) -C .. deepcoin_qt
